const mongoose = require("mongoose");

const dataSchema = new mongoose.Schema(
{
  email: { type: mongoose.Schema.Types.Mixed, default: null },
  latitude: { type: mongoose.Schema.Types.Mixed, default: null },
  longitude: { type: mongoose.Schema.Types.Mixed, default: null },
  startDate: { type: mongoose.Schema.Types.Mixed, default: null },
  startTime: { type: mongoose.Schema.Types.Mixed, default: null },
  backST: { type: mongoose.Schema.Types.Mixed, default: null },
  backSD: { type: mongoose.Schema.Types.Mixed, default: null },
  name: { type: mongoose.Schema.Types.Mixed, default: null },
  address: { type: mongoose.Schema.Types.Mixed, default: null },
  contact: { type: mongoose.Schema.Types.Mixed, default: null },
  interviewerName: { type: mongoose.Schema.Types.Mixed, default: null },
  interviewerId: { type: mongoose.Schema.Types.Mixed, default: null },
  city: { type: mongoose.Schema.Types.Mixed, default: null },
  language: { type: mongoose.Schema.Types.Mixed, default: null },
  QS: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1: { type: mongoose.Schema.Types.Mixed, default: null },
  Q2a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q2b: { type: mongoose.Schema.Types.Mixed, default: null },
  Q2b_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q3: { type: mongoose.Schema.Types.Mixed, default: null },
  Q4: { type: mongoose.Schema.Types.Mixed, default: null },
  Q5: { type: mongoose.Schema.Types.Mixed, default: null },
  Q6: { type: mongoose.Schema.Types.Mixed, default: null },
  Q7: { type: mongoose.Schema.Types.Mixed, default: null },
  Q8: { type: mongoose.Schema.Types.Mixed, default: null },
  Q9: { type: mongoose.Schema.Types.Mixed, default: null },
  Q9_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q10: { type: mongoose.Schema.Types.Mixed, default: null },
  Q11: { type: mongoose.Schema.Types.Mixed, default: null },
  Q12: { type: mongoose.Schema.Types.Mixed, default: null },
  TC_mode: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_4_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_5_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ1_total: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_4_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_3_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ3_4_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  TCQ4_3_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ1: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_1_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_2_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_3_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_1_main_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_2_main_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQPOE_3_main_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_1_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_2_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_3_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_1_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_2_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQTE_3_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_1_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_2_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_3_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_1_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_2_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQRR_3_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_1_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_2_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_3_cost: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_1_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_2_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQMR_3_reason: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_1_Ans3: { type: mongoose.Schema.Types.Mixed, default: null },
  SCQ6_2_Ans3: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_3_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_4_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_5_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_6_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_7_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_4_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_5_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_6_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  IC_7_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ1: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ2: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ3: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ3_other: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ4: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ4_a: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ5: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ5a: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ5b: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ6: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ6a: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ7_1_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ7_2_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ7_3_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  DCQ7_4_Ans: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_1_option: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_2_option: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_3_option: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_4_option: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_3_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ1_4_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ2: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ3: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ4: { type: mongoose.Schema.Types.Mixed, default: null },
  STQ5: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_1_option: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_2_option: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_3_option: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_4_option: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_5_option: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_1_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_2_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_3_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_4_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_5_Ans2: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_6: { type: mongoose.Schema.Types.Mixed, default: null },
  Q1res_6a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q2res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q2res_a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q3res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q3res_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q3res_a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q4res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q4res_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q5res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q5res_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q6res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q6res_other: { type: mongoose.Schema.Types.Mixed, default: null },
  Q7res_a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q7res_b: { type: mongoose.Schema.Types.Mixed, default: null },
  Q8res: { type: mongoose.Schema.Types.Mixed, default: null },
  Q9res_a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q9res_b: { type: mongoose.Schema.Types.Mixed, default: null },
  Q10res_a: { type: mongoose.Schema.Types.Mixed, default: null },
  Q10res_b: { type: mongoose.Schema.Types.Mixed, default: null },
  endTime: { type: mongoose.Schema.Types.Mixed, default: null },
  endDate: { type: mongoose.Schema.Types.Mixed, default: null },
  duration: { type: mongoose.Schema.Types.Mixed, default: null },
  backET: { type: mongoose.Schema.Types.Mixed, default: null },
  backED: { type: mongoose.Schema.Types.Mixed, default: null },
},
  { timestamps: true }
);
const DataModel = mongoose.model("Data", dataSchema);

module.exports = { DataModel };
// {
//   "email": "admin",
//   "latitude": 18.5196,
//   "longitude": 73.8554,
//   "startDate": "13/05/2025",
//   "startTime": "6:20:31 PM",
//   "backST": "18:20:31",
//   "backSD": "13-05-2025",
//   "name": "b45",
//   "address": "hn",
//   "contact": "3333333333",
//   "interviewerName": "nhn",
//   "interviewerId": "hn",
//   "city": "Pune",
//   "language": "en",
//   "QS": "12",
//   "Q1": "1",
//   "Q2a": "B7",
//   "Q2b": "E",
//   "Q2b_other": "wee",
//   "Q3": "3",
//   "Q4": "2025-05-03",
//   "Q5": "434",
//   "Q6": "434",
//   "Q7": "12",
//   "Q8": "1",
//   "Q9": "4",
//   "Q9_other": "3434",
//   "Q10": "2025-05-10",
//   "Q11": "2025-05-11",
//   "Q12": "2025-05-23",
//   "TC_mode": "1",
//   "TCQ1_1_Ans": "34",
//   "TCQ1_2_Ans": "3",
//   "TCQ1_3_Ans": "43",
//   "TCQ1_4_Ans": "43",
//   "TCQ1_5_Ans": "4",
//   "TCQ1_total": 127,
//   "TCQ2": [
//       "16",
//       "13"
//   ],
//   "TCQ3_1_Ans": "44",
//   "TCQ3_1_Ans2": "6",
//   "TCQ3_2_Ans": "6",
//   "TCQ3_3_Ans": "4",
//   "TCQ3_4_Ans": "77",
//   "TCQ3_3_Ans2": "6",
//   "TCQ3_2_Ans2": "6",
//   "TCQ3_4_Ans2": "6",
//   "TCQ4_1_Ans": "yty",
//   "TCQ4_2_Ans": "yt",
//   "TCQ4_1_Ans2": "56y",
//   "TCQ4_2_Ans2": "65y",
//   "TCQ4_3_Ans": "yt",
//   "TCQ4_3_Ans2": "656y",
//   "SCQ1": [
//       "1",
//       "2",
//       "3",
//       "4"
//   ],
//   "SCQPOE_1_Ans": "bg",
//   "SCQPOE_2_Ans": "bgb",
//   "SCQPOE_3_Ans": "bgb",
//   "SCQPOE_1_cost": "454",
//   "SCQPOE_2_cost": "4345",
//   "SCQPOE_3_cost": "65",
//   "SCQPOE_1_main_cost": "545",
//   "SCQPOE_2_main_cost": "545",
//   "SCQPOE_3_main_cost": "45",
//   "SCQTE_1_Ans": "54",
//   "SCQTE_2_Ans": "545",
//   "SCQTE_3_Ans": "54",
//   "SCQTE_1_cost": "54",
//   "SCQTE_2_cost": "54",
//   "SCQTE_3_cost": "54",
//   "SCQTE_1_reason": "fff",
//   "SCQTE_2_reason": "fef",
//   "SCQTE_3_reason": "fef",
//   "SCQRR_1_Ans": "fef",
//   "SCQRR_2_Ans": "fe",
//   "SCQRR_3_Ans": "fef",
//   "SCQRR_1_cost": "4",
//   "SCQRR_2_cost": "5",
//   "SCQRR_3_cost": "33",
//   "SCQRR_1_reason": "de",
//   "SCQRR_2_reason": "dd",
//   "SCQRR_3_reason": "dd",
//   "SCQMR_1_Ans": "fff",
//   "SCQMR_2_Ans": "ff",
//   "SCQMR_3_Ans": "ff",
//   "SCQMR_1_cost": "45",
//   "SCQMR_2_cost": "545",
//   "SCQMR_3_cost": "545",
//   "SCQMR_1_reason": "54",
//   "SCQMR_2_reason": "45",
//   "SCQMR_3_reason": "545",
//   "SCQ6_1_Ans": "dd",
//   "SCQ6_2_Ans": "dd",
//   "SCQ6_1_Ans2": "34",
//   "SCQ6_2_Ans2": "434",
//   "SCQ6_1_Ans3": "434",
//   "SCQ6_2_Ans3": "434",
//   "IC_1_Ans": "434",
//   "IC_1_Ans2": "rrr",
//   "IC_2_Ans": "34",
//   "IC_2_Ans2": "4g34",
//   "IC_3_Ans": "434",
//   "IC_3_Ans2": "434g",
//   "IC_4_Ans": "44",
//   "IC_5_Ans": "44",
//   "IC_6_Ans": "44",
//   "IC_7_Ans": "44",
//   "IC_4_Ans2": "gg",
//   "IC_5_Ans2": "ggg",
//   "IC_6_Ans2": "ggg",
//   "IC_7_Ans2": "ggg",
//   "DCQ1": "2",
//   "DCQ2": "3434",
//   "DCQ3": "1",
//   "DCQ3_other": "4344",
//   "DCQ4": "2",
//   "DCQ4_a": "44",
//   "DCQ5": "1",
//   "DCQ5a": "44",
//   "DCQ5b": "44",
//   "DCQ6": "2",
//   "DCQ6a": "44dd",
//   "DCQ7_1_Ans": "434",
//   "DCQ7_2_Ans": "434",
//   "DCQ7_3_Ans": "433",
//   "DCQ7_4_Ans": "434",
//   "STQ1_1_option": "2",
//   "STQ1_2_option": "2",
//   "STQ1_3_option": "1",
//   "STQ1_4_option": "2",
//   "STQ1_1_Ans2": "4",
//   "STQ1_2_Ans2": "55",
//   "STQ1_3_Ans2": "55",
//   "STQ1_4_Ans2": "55",
//   "STQ2": "1",
//   "STQ3": "34",
//   "STQ4": "434",
//   "STQ5": "434",
//   "Q1res_1_option": "2",
//   "Q1res_2_option": "2",
//   "Q1res_3_option": "1",
//   "Q1res_4_option": "2",
//   "Q1res_5_option": "2",
//   "Q1res_1_Ans2": "34",
//   "Q1res_2_Ans2": "434",
//   "Q1res_3_Ans2": "rr",
//   "Q1res_4_Ans2": "rr",
//   "Q1res_5_Ans2": "rr",
//   "Q1res_6": "2",
//   "Q1res_6a": "2",
//   "Q2res": "1",
//   "Q2res_a": "34434",
//   "Q3res": "1",
//   "Q3res_other": "33555",
//   "Q3res_a": "545",
//   "Q4res": [
//       "3",
//       "8"
//   ],
//   "Q4res_other": "545",
//   "Q5res": [
//       "14",
//       "11"
//   ],
//   "Q5res_other": "545",
//   "Q6res": "1",
//   "Q6res_other": "54545",
//   "Q7res_a": "545",
//   "Q7res_b": "545",
//   "Q8res": "545",
//   "Q9res_a": "545",
//   "Q9res_b": "545",
//   "Q10res_a": "ggg",
//   "Q10res_b": "gg",
//   "endTime": "6:42:44 PM",
//   "endDate": "13/05/2025",
//   "duration": "00:22:13",
//   "backET": "18:42:46",
//   "backED": "13-05-2025"
// }
